name: eye state environment
channels:
  - defaults
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - absl-py=2.2.0=pyhd8ed1ab_0
  - aiohappyeyeballs=2.6.1=pyhd8ed1ab_0
  - aiohttp=3.11.16=py39hd18e689_0
  - aiosignal=1.3.2=pyhd8ed1ab_0
  - aom=3.6.0=hf0c8a7f_0
  - appdirs=1.4.4=pyhd8ed1ab_1
  - appnope=0.1.4=pyhd8ed1ab_1
  - arrow-cpp=19.0.0=h2a1e5b1_1
  - asttokens=3.0.0=pyhd8ed1ab_1
  - astunparse=1.6.3=pyhd8ed1ab_3
  - async-timeout=5.0.1=pyhd8ed1ab_1
  - attrs=25.3.0=pyh71513ae_0
  - aws-c-auth=0.6.21=hbc0b158_0
  - aws-c-cal=0.5.20=hdc31e88_3
  - aws-c-common=0.8.5=hb7f2c08_0
  - aws-c-compression=0.2.16=hfb1f584_0
  - aws-c-event-stream=0.2.15=h6beef47_11
  - aws-c-http=0.6.27=h40fbe91_3
  - aws-c-io=0.13.11=hb3bb6ef_2
  - aws-c-mqtt=0.7.13=h95fd635_9
  - aws-c-s3=0.2.1=h9f2fa91_0
  - aws-c-sdkutils=0.1.7=hfb1f584_0
  - aws-checksums=0.1.13=hfb1f584_5
  - aws-crt-cpp=0.18.16=h8755ad4_2
  - aws-sdk-cpp=1.11.212=h9475118_0
  - beautifulsoup4=4.13.3=pyha770c72_0
  - blas=2.120=openblas
  - blas-devel=3.9.0=20_osx64_openblas
  - blosc=1.21.3=hcec6c5f_0
  - bokeh=3.4.2=pyhd8ed1ab_0
  - boost-cpp=1.82.0=ha357a0b_2
  - brotli=1.0.9=hb7f2c08_9
  - brotli-bin=1.0.9=hb7f2c08_9
  - brotli-python=1.0.9=py39h7a8716b_9
  - brunsli=0.1=h046ec9c_0
  - bzip2=1.0.8=hfdf4475_7
  - c-ares=1.34.4=hf13058a_0
  - ca-certificates=2025.2.25=hecd8cb5_0
  - cairo=1.16.0=h3ce6f7e_5
  - certifi=2025.4.26=py39hecd8cb5_0
  - cffi=1.17.1=py39h8ddeee6_0
  - cfitsio=3.470=h01dc385_7
  - charls=2.2.0=h046ec9c_0
  - charset-normalizer=3.4.1=pyhd8ed1ab_0
  - click=8.1.8=pyh707e725_0
  - cloudpickle=3.1.1=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - comm=0.2.2=pyhd8ed1ab_1
  - contourpy=1.2.1=py39h1962661_1
  - cryptography=44.0.2=py39hce2744d_0
  - cvxopt=1.3.2=py39hfaca71d_3
  - cvxpy=1.3.1=py39h6e9494a_0
  - cvxpy-base=1.3.1=py39hecff1ad_0
  - cycler=0.12.1=pyhd8ed1ab_1
  - cyrus-sasl=2.1.27=h1e973b7_6
  - cytoolz=1.0.1=py39h80efdc8_0
  - dask=2024.8.0=pyhd8ed1ab_0
  - dask-core=2024.8.0=pyhd8ed1ab_0
  - dask-expr=1.1.10=pyhd8ed1ab_0
  - datasets=3.5.0=pyhd8ed1ab_0
  - dav1d=1.2.1=h0dc2134_0
  - debugpy=1.6.7=py39h7a8716b_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - dill=0.3.8=pyhd8ed1ab_0
  - distributed=2024.8.0=pyhd8ed1ab_0
  - docopt=0.6.2=pyhd8ed1ab_2
  - dsdp=5.8=h6e329d1_1203
  - ecos=2.0.14=py39hff9a475_1
  - eigen=3.4.0=h940c156_0
  - exceptiongroup=1.2.2=pyhd8ed1ab_1
  - executing=2.1.0=pyhd8ed1ab_1
  - expat=2.7.0=h240833e_0
  - fancyimpute=0.7.0=pyhd8ed1ab_0
  - ffmpeg=6.1.1=hd2ef4e1_3
  - fftw=3.3.10=nompi_h4fa670e_109
  - filelock=3.18.0=pyhd8ed1ab_0
  - flatbuffers=24.3.25=h6d0c2b6_0
  - fontconfig=2.14.1=h269ac6a_3
  - fonttools=4.56.0=py39hd18e689_0
  - freetype=2.13.3=h02243ff_0
  - fribidi=1.0.10=hbcb3906_0
  - frozendict=2.4.6=py39h296a897_0
  - frozenlist=1.5.0=py39hd18e689_1
  - fsspec=2024.12.0=pyhd8ed1ab_0
  - future=1.0.0=pyhd8ed1ab_2
  - gast=0.6.0=pyhd8ed1ab_0
  - gdk-pixbuf=2.42.10=he00a9fc_0
  - gettext=0.21.1=h8a4c099_0
  - gflags=2.2.2=hb1e8313_1004
  - giflib=5.2.2=h10d778d_0
  - gitdb=4.0.12=pyhd8ed1ab_0
  - gitpython=3.1.44=pyhff2d567_0
  - glib=2.78.4=hcec6c5f_0
  - glib-tools=2.78.4=hcec6c5f_0
  - glog=0.5.0=h25b26a9_0
  - glpk=5.0=h3cb5acd_0
  - gmp=6.3.0=h6d0c2b6_0
  - google-pasta=0.2.0=pyhd8ed1ab_2
  - graphite2=1.3.14=he9d5cce_1
  - greenlet=2.0.2=py39h7a8716b_0
  - grpcio=1.62.2=py39hab2016f_0
  - gsl=2.7=h93259b0_0
  - gst-plugins-base=1.14.5=hb4a159a_2
  - gstreamer=1.14.5=h06b91d7_2
  - h2=4.2.0=pyhd8ed1ab_0
  - h5py=3.12.1=py39h6c1bcc5_1
  - harfbuzz=10.2.0=h5b8c2d6_0
  - hdf5=1.14.5=h80586a8_2
  - hpack=4.1.0=pyhd8ed1ab_0
  - html5lib=1.1=pyhd8ed1ab_2
  - huggingface_hub=0.30.1=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=73.2=hf5e326d_0
  - idna=3.10=pyhd8ed1ab_1
  - imagecodecs=2024.9.22=py39h88dd9b7_0
  - imageio=2.37.0=pyhfb79c49_0
  - importlib-metadata=8.6.1=pyha770c72_0
  - importlib_metadata=8.6.1=hd8ed1ab_0
  - importlib_resources=6.5.2=pyhd8ed1ab_0
  - iniconfig=2.0.0=pyhd8ed1ab_1
  - ipykernel=6.29.5=pyh57ce528_0
  - ipython=8.18.1=pyh707e725_3
  - jedi=0.19.2=pyhd8ed1ab_1
  - jinja2=3.1.6=pyhd8ed1ab_0
  - joblib=1.4.2=pyhd8ed1ab_1
  - jpeg=9e=hb7f2c08_3
  - jsonpickle=4.0.0=pyh29332c3_0
  - jsonschema=4.23.0=pyhd8ed1ab_1
  - jsonschema-specifications=2024.10.1=pyhd8ed1ab_1
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.7.2=pyh31011fe_1
  - jxrlib=1.1=h10d778d_3
  - keras=3.9.0=pyh753f3f9_0
  - kiwisolver=1.4.4=py39h92daf61_1
  - knnimpute=0.1.0=pyhd8ed1ab_0
  - krb5=1.20.1=h049b76e_0
  - lame=3.100=hb7f2c08_1003
  - lazy-loader=0.4=pyhd8ed1ab_2
  - lazy_loader=0.4=pyhd8ed1ab_2
  - lcms2=2.16=h4f63f0c_0
  - leptonica=1.82.0=hf15457e_2
  - lerc=4.0.0=hb486fe8_0
  - libabseil=20240116.2=cxx17_h548131f_0
  - libaec=1.1.3=h6d0c2b6_0
  - libarchive=3.7.7=h4c66a04_0
  - libavif=1.1.1=h46256e1_0
  - libblas=3.9.0=20_osx64_openblas
  - libboost=1.82.0=hf53b9f2_2
  - libbrotlicommon=1.0.9=hb7f2c08_9
  - libbrotlidec=1.0.9=hb7f2c08_9
  - libbrotlienc=1.0.9=hb7f2c08_9
  - libcblas=3.9.0=20_osx64_openblas
  - libclang=14.0.6=default_h55ffa42_0
  - libclang13=14.0.6=default_hb5731bd_0
  - libcurl=8.12.1=h9bcc28a_0
  - libcxx=14.0.6=h9765a3e_0
  - libdeflate=1.22=h00291cd_0
  - libedit=3.1.20230828=h6c40b1e_0
  - libev=4.33=h10d778d_2
  - libevent=2.1.12=ha90c15b_1
  - libexpat=2.7.0=h240833e_0
  - libffi=3.4.4=hecd8cb5_1
  - libgfortran=5.0.0=14_2_0_h51e75f0_2
  - libgfortran5=14.2.0=h51e75f0_2
  - libglib=2.78.4=h19e1a8f_0
  - libgrpc=1.62.2=hf2926fd_0
  - libiconv=1.18=h4b5e92a_1
  - liblapack=3.9.0=20_osx64_openblas
  - liblapacke=3.9.0=20_osx64_openblas
  - libllvm10=10.0.1=h009f743_3
  - libllvm14=14.0.6=h26321d7_4
  - libnghttp2=1.57.0=h9beae6a_0
  - libntlm=1.8=h6e16a3a_0
  - libogg=1.3.5=hfdf4475_0
  - libopenblas=0.3.25=openmp_hfef2a42_0
  - libopus=1.3.1=hc929b4f_1
  - libpng=1.6.39=h6c40b1e_0
  - libpq=17.4=h184c1cd_0
  - libprotobuf=4.25.3=h34eed0b_0
  - libqdldl=0.1.5=hf0c8a7f_1
  - librsvg=2.56.3=ha9ee93f_1
  - libsodium=1.0.18=hbcb3906_1
  - libssh2=1.11.1=h3a17b82_0
  - libtheora=1.1.1=hfdf4475_1006
  - libthrift=0.15.0=h70b4b81_2
  - libtiff=4.5.1=h6fa9cd1_1
  - libvorbis=1.3.7=h046ec9c_0
  - libvpx=1.13.1=hcec6c5f_0
  - libwebp=1.3.2=hf6ce154_0
  - libwebp-base=1.3.2=h10d778d_1
  - libxml2=2.13.5=h6070cd6_0
  - libxslt=1.1.39=h03b04e6_0
  - libzopfli=1.0.3=h046ec9c_0
  - llvm-openmp=20.1.2=ha54dae1_0
  - llvmlite=0.36.0=py39h798a4f4_0
  - locket=1.0.0=pyhd8ed1ab_0
  - lxml=4.9.1=py39h701faf5_0
  - lz4=4.3.3=py39ha7ca277_1
  - lz4-c=1.9.4=hf0c8a7f_0
  - markdown=3.6=pyhd8ed1ab_0
  - markdown-it-py=3.0.0=pyhd8ed1ab_1
  - markupsafe=3.0.2=py39hd18e689_1
  - matplotlib=3.5.1=py39hecd8cb5_1
  - matplotlib-base=3.5.1=py39hfb0c5b7_1
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - mdurl=0.1.2=pyhd8ed1ab_1
  - missingno=0.5.2=pyhd8ed1ab_0
  - ml_dtypes=0.4.0=py39h207f725_0
  - mpfr=4.2.1=haed47dc_3
  - msgpack-python=1.0.5=py39h92daf61_0
  - multidict=6.2.0=py39h781ac47_0
  - multiprocess=0.70.16=py39h06d86d0_1
  - multitasking=0.0.9=pyhd8ed1ab_0
  - munch=4.0.0=pyhd8ed1ab_1
  - munkres=1.1.4=pyh9f0ad1d_0
  - mysql=8.4.0=hbfece55_1
  - namex=0.0.8=pyhd8ed1ab_1
  - narwhals=1.33.0=pyhd8ed1ab_0
  - nbformat=5.10.4=pyhd8ed1ab_1
  - ncurses=6.4=hcec6c5f_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - networkx=3.2.1=pyhd8ed1ab_0
  - nose=1.3.7=py_1006
  - numba=0.53.0=py39hb2f4e1b_0
  - numpy=1.24.2=py39h6ee2318_0
  - openblas=0.3.25=openmp_h6794695_0
  - opencv=4.10.0=py39h21ae996_2
  - openh264=2.1.1=hfd3ada9_0
  - openjpeg=2.5.2=hbf2204d_0
  - openldap=2.6.4=hd88b477_0
  - openssl=3.4.1=hc426f3f_0
  - opt_einsum=3.4.0=pyhd8ed1ab_1
  - orc=2.0.1=h5747287_0
  - osqp=0.6.2.post0=py39h4d6be9b_3
  - packaging=24.2=pyhd8ed1ab_2
  - pandas=2.0.0=py39hecff1ad_0
  - pango=1.50.7=h986b0af_1
  - parso=0.8.4=pyhd8ed1ab_1
  - partd=1.4.2=pyhd8ed1ab_0
  - patsy=1.0.1=pyhd8ed1ab_1
  - pcre2=10.42=h9b97e30_1
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pillow=11.1.0=py39h47bf62f_0
  - pip=25.0=py39hecd8cb5_0
  - pixman=0.40.0=hbcb3906_0
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_2
  - platformdirs=4.3.7=pyh29332c3_0
  - plotly=6.0.1=pyhd8ed1ab_0
  - pluggy=1.5.0=pyhd8ed1ab_1
  - progressbar2=4.5.0=pyhd8ed1ab_1
  - prompt-toolkit=3.0.50=pyha770c72_0
  - propcache=0.2.1=py39hd18e689_1
  - protobuf=4.25.3=py39h149b2d4_1
  - psutil=7.0.0=py39h80efdc8_0
  - psycopg2=2.9.9=py39hdc4deee_2
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - py-cpuinfo=9.0.0=pyhd8ed1ab_1
  - pyarrow=19.0.0=py39h6d0c2b6_1
  - pyarrow-hotfix=0.6=pyhd8ed1ab_1
  - pybind11=2.13.6=pyh1ec8472_2
  - pybind11-global=2.13.6=pyh415d2e4_2
  - pycparser=2.22=pyh29332c3_1
  - pygam=0.9.0=pyhd8ed1ab_2
  - pygments=2.19.1=pyhd8ed1ab_0
  - pyparsing=3.2.3=pyhd8ed1ab_1
  - pysocks=1.7.1=pyha55dd90_7
  - pytest=8.3.5=pyhd8ed1ab_0
  - python=3.9.21=hce00570_1
  - python-dateutil=2.9.0.post0=pyhff2d567_1
  - python-dotenv=1.1.0=pyh29332c3_1
  - python-fastjsonschema=2.21.1=pyhd8ed1ab_0
  - python-flatbuffers=25.2.10=pyhbc23db3_0
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python-utils=3.9.1=pyhff2d567_1
  - python-xxhash=3.5.0=py39h80efdc8_2
  - python_abi=3.9=2_cp39
  - pytz=2025.2=pyhd8ed1ab_0
  - pywavelets=1.6.0=py39hb943cd9_0
  - pyyaml=6.0.2=py39hd18e689_2
  - pyzmq=25.1.1=py39h53dde38_2
  - qdldl-python=0.1.5.post2=py39hecff1ad_0
  - qt-main=5.15.2=hf83fbd5_12
  - re2=2022.04.01=h96cf925_0
  - readline=8.2=hca72f7f_0
  - referencing=0.36.2=pyh29332c3_0
  - regex=2024.11.6=py39h80efdc8_0
  - requests=2.32.3=pyhd8ed1ab_1
  - rich=14.0.0=pyh29332c3_0
  - rpds-py=0.24.0=py39h0cc59c6_0
  - sacred=0.8.5=pyhd8ed1ab_0
  - safetensors=0.5.3=py39hd8827cb_0
  - scikit-image=0.20.0=py39h75c1baf_1
  - scikit-learn=1.2.2=py39h151e6e4_1
  - scipy=1.9.1=py39h9488793_0
  - scs=3.2.7.post2=default_py39hbfa5a08_0
  - seaborn=0.13.2=hd8ed1ab_3
  - seaborn-base=0.13.2=pyhd8ed1ab_3
  - setuptools=75.8.0=py39hecd8cb5_0
  - shap=0.41.0=py39hf72b562_0
  - six=1.17.0=pyhd8ed1ab_0
  - slicer=0.0.7=pyhd8ed1ab_0
  - smmap=5.0.2=pyhd8ed1ab_0
  - snappy=1.2.1=h6d0c2b6_0
  - sortedcontainers=2.4.0=pyhd8ed1ab_1
  - soupsieve=2.5=pyhd8ed1ab_1
  - sqlalchemy=2.0.40=py39h80efdc8_0
  - sqlite=3.45.3=h6c40b1e_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - statsmodels=0.14.4=py39hff9a475_0
  - suitesparse=7.8.3=hc0451fe_0
  - tbb=2022.0.0=h1962661_0
  - tblib=3.1.0=pyhd8ed1ab_0
  - tensorboard=2.17.1=pyhd8ed1ab_0
  - tensorboard-data-server=0.7.0=py39hb2b0753_2
  - tensorflow=2.17.0=cpu_py39hb3d9b59_0
  - tensorflow-base=2.17.0=cpu_py39ha37eea7_0
  - tensorflow-estimator=2.17.0=cpu_py39h7aa49ff_0
  - termcolor=3.0.0=pyhd8ed1ab_0
  - tesseract=5.2.0=h6d0c2b6_2
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tifffile=2024.6.18=pyhd8ed1ab_0
  - tk=8.6.14=h4d00af3_0
  - tokenizers=0.21.0=py39h753fa65_0
  - tomli=2.2.1=pyhd8ed1ab_1
  - toolz=1.0.0=pyhd8ed1ab_1
  - tornado=6.4.2=py39h80efdc8_0
  - tqdm=4.67.1=pyhd8ed1ab_1
  - traitlets=5.14.3=pyhd8ed1ab_1
  - transformers=4.50.0=pyhd8ed1ab_0
  - tzdata=2025a=h04d1e81_0
  - unicodedata2=16.0.0=py39h80efdc8_0
  - urllib3=2.3.0=pyhd8ed1ab_0
  - utf8proc=2.6.1=h6c40b1e_1
  - wcwidth=0.2.13=pyhd8ed1ab_1
  - webencodings=0.5.1=pyhd8ed1ab_3
  - werkzeug=3.1.3=pyhd8ed1ab_1
  - wheel=0.45.1=py39hecd8cb5_0
  - wrapt=1.17.2=py39h80efdc8_0
  - xxhash=0.8.3=h6e16a3a_0
  - xyzservices=2025.1.0=pyhd8ed1ab_0
  - xz=5.6.4=h46256e1_1
  - yaml=0.2.5=h0d85af4_2
  - yarl=1.18.3=py39hd18e689_1
  - yfinance=0.2.28=pyhd8ed1ab_0
  - zeromq=4.3.5=hcec6c5f_0
  - zfp=1.0.0=ha894c9a_3
  - zict=3.0.0=pyhd8ed1ab_1
  - zipp=3.21.0=pyhd8ed1ab_1
  - zlib=1.2.13=h4b97444_1
  - zlib-ng=2.0.7=hb7f2c08_0
  - zstandard=0.23.0=py39h80efdc8_1
  - zstd=1.5.6=h138b38a_0
  - pip:
      - faraway==0.0.6
      - imbalanced-learn==0.12.4
      - mpmath==1.3.0
      - optree==0.10.0
      - sympy==1.13.3
      - typing-extensions==4.14.0
      - xgboost==2.1.4
